filter:
  excluded_paths:
  - tests/*
  - apigen/*
  - dummy-data/*
  - i18n/*
  - includes/api/v1/*
  - includes/libraries/*
  - includes/updates/*
  - includes/gateways/simplify-commerce/includes/*

checks:
  php:
    variable_existence: false
    verify_access_scope_valid: false
    verify_argument_usable_as_reference: false
    verify_property_names: false
    no_global_keyword: false
    psr2_switch_declaration: false
    psr2_control_structure_declaration: false
    psr2_class_declaration: false
    one_class_per_file: false
    no_exit: false
    avoid_superglobals: false
    avoid_closing_tag: false
    upper_lower_casing:
      keywords:
        general: lower
      constants:
        true_false_null: lower

tools:
  sensiolabs_security_checker: true
  php_code_sniffer:
    config:
      standard: "WordPress"
  external_code_coverage:
    timeout: 600