filter:
  excluded_paths:
    - tests/*
    - apigen/*
    - dummy-data/*
    - i18n/*
    - includes/api/v1/*
    - includes/libraries/*
    - includes/updates/*
    - includes/gateways/simplify-commerce/includes/*

checks:
  php:
    code_rating: true
    duplication: true
    psr2_switch_declaration: false
    psr2_control_structure_declaration: false
    psr2_class_declaration: false
    one_class_per_file: false
    avoid_superglobals: false
    require_php_tag_first: false

tools:
  external_code_coverage:
    timeout: 600
    php_code_sniffer:
        config:
            standard: "WordPress"