filter:
  excluded_paths:
    - tests/*
    - apigen/*
    - dummy-data/*
    - i18n/*
    - includes/api/v1/*
    - includes/libraries/*
    - includes/updates/*
    - includes/gateways/simplify-commerce/includes/*

checks:
  php:
    code_rating: true
    duplication: true
    code_rating: true
    duplication: true
    psr2_switch_declaration: false
    psr2_control_structure_declaration: false
    psr2_class_declaration: false
    one_class_per_file: false
    avoid_superglobals: false
    require_php_tag_first: false

tools:
  external_code_coverage:
    timeout: 600

coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            around_operators:
                negation: true
            within:
                brackets: true
                array_initializer: true
                grouping: true
                function_call: true
                function_declaration: true
                if: true
                for: true
                while: true
                switch: true
                catch: true
        braces:
            classes_functions:
                class: end-of-line
                function: end-of-line
                closure: end-of-line
            if:
                opening: end-of-line
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: upper
