build:
  environment:
    php: '7.1'
    mysql: true
    postgresql: false
    redis: false
    apache2:
      modules: ['rewrite']
    variables:
      WP_VERSION: 'latest'
  dependencies:
    before:
    - bash tests/bin/install.sh woocommerce_test root '' localhost $WP_VERSION
  tests:
    override:
    -
      command: 'vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=results'
      coverage:
        file: 'results'
        format: 'clover'

tools:
  sensiolabs_security_checker: true
  php_code_sniffer:
    config:
      standard: WordPress

checks:
  php:
    variable_existence: false
    verify_access_scope_valid: false
    verify_argument_usable_as_reference: false
    verify_property_names: false
    no_global_keyword: false
    psr2_switch_declaration: false
    psr2_control_structure_declaration: false
    psr2_class_declaration: false
    one_class_per_file: false
    no_exit: false
    avoid_superglobals: false
    avoid_closing_tag: false
    coding_standard:
      name: WordPress

filter:
  excluded_paths:
  - tests/*
  - apigen/*
  - dummy-data/*
  - i18n/*
  - includes/api/legacy/*
  - includes/legacy/*
  - includes/libraries/*
  - includes/updates/*
  - includes/gateways/simplify-commerce/*
  - includes/shipping/legacy-*
  - includes/wc-deprecated-functions.php
  - includes/class-wc-legacy-api.php
