language: php

sudo: false

# Test main supported versions of PHP against latest WP.
php:
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0 PHP_LATEST_STABLE=7.1

# Additional tests against stable PHP (min recommended version is 5.6) and past supported versions of WP.
matrix:
  include:
  - php: 5.3
    dist: precise
  - php: 5.2
    dist: precise

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - if [[ $TRAVIS_PHP_VERSION == '7.1' ]]; then composer install; fi
  - bash tests/bin/install.sh woocommerce_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

script:
  - bash tests/bin/phpunit.sh
  - bash tests/bin/phpcs.sh

after_script:
  - bash tests/bin/travis.sh after
