language: php

sudo: false

# Test main supported versions of PHP and HHVM against latest WP. 5.2 is min supported version.
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0

# Additonal tests against stable PHP (min recommended version is 5.6) and past supported versions of WP.
matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash tests/bin/install.sh woocommerce_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

script:
  # Search for PHP syntax errors.
  - find . \( -name '*.php' -not -path "./vendor/*" \) -exec php -lf {} \;
  # Run PHPUnit tests.
  - phpunit -c phpunit.xml.dist
  # WordPress Coding Standards.
  # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
  # @link http://pear.php.net/package/PHP_CodeSniffer/
  # -p flag: Show progress of the run.
  # -s flag: Show sniff codes in all reports.
  # -v flag: Print verbose output.
  # -n flag: Do not print warnings. (shortcut for --warning-severity=0)
  # --standard: Use WordPress as the standard.
  # --extensions: Only sniff PHP files.
  - /tmp/phpcs/scripts/phpcs -p -s -v -n ./*.php --standard=./phpcs.ruleset.xml --extensions=php
  - /tmp/phpcs/scripts/phpcs -p -s -v -n ./**/*.php --standard=./phpcs.ruleset.xml --extensions=php
  - /tmp/phpcs/scripts/phpcs -p -s -v -n ./**/**/*.php --standard=./phpcs.ruleset.xml --extensions=php
  - /tmp/phpcs/scripts/phpcs -p -s -v -n ./**/**/**/*.php --standard=./phpcs.ruleset.xml --extensions=php

after_script:
  - bash tests/bin/travis.sh after
