language: php

sudo: false

# Test main supported versions of PHP against latest WP.
php:
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0 PHP_LATEST_STABLE=7.1

# Additional tests against stable PHP (min recommended version is 5.6) and past supported versions of WP.
matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1 PHP_LATEST_STABLE=7.1
    dist: precise
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=0 PHP_LATEST_STABLE=7.1
    dist: precise
  - php: 5.2
    env: WP_VERSION=latest WP_MULTISITE=0 PHP_LATEST_STABLE=7.1
    dist: precise

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit --version
  - phpunit -c phpunit.xml
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - bash tests/bin/travis.sh after

after_success:
    - bash <(curl -s https://codecov.io/bash)
