language: php

sudo: false

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=0

matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1

before_install:
  - php composer self-update

before_script:
  - bash tests/bin/install.sh woocommerce_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

script: phpunit -c phpunit.xml.dist

after_script:
  - bash tests/bin/travis.sh after
