name: Add Community Label

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]
  

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-20.04
    outputs:
      issueId: ${{ steps.check.outputs.issueId }}
      run: ${{ steps.check.outputs.run }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        id: check
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93

      - name: Install Octokit 
        run: npm --prefix .github/workflows/scripts install @octokit/action

      - name: Check if user is a community contributor
        run: node .github/workflows/scripts/is-community-contributor.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
