name: Add Community Label

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]
  

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93

      - name: Install Octokit 
        run: npm --prefix .github/workflows/scripts install @octokit/action

      - name: Check if user is a community contributor
        id: check
        run: node .github/workflows/scripts/is-community-contributor.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: "If community PR, assign a reviewer"
        if: github.event.pull_request && steps.check.outputs.is-community == 'yes'
        uses: shufo/auto-assign-reviewer-by-files@24a9fcbd5c51c4403b64c8b6e087c824b67a5c35
        with:
          config: ".github/project-community-pr-assigner.yml"
          token: ${{ secrets.GITHUB_TOKEN }}
