name: Run code sniff on PR
on:
  pull_request
defaults:
  run:
    shell: bash
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Code sniff (PHP 7.4, WP Latest)
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v32  
        with:
          files: |
            **/*.php

      - name: Setup WooCommerce Monorepo
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./.github/actions/setup-woocommerce-monorepo
        with:
          build: false

      - name: Tool versions
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          php --version
          composer --version

      - name: Run PHPCS
        if: steps.changed-files.outputs.any_changed == 'true'
        run: ./plugins/woocommerce/vendor/bin/phpcs -n -q --report=checkstyle ${{ steps.changed-files.outputs.all_changed_files }} | cs2pr        
