name: Run code sniff on PR
on:
  pull_request
defaults:
  run:
    shell: bash
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Code sniff (PHP 7.4, WP Latest)
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup WooCommerce Monorepo
        uses: ./.github/actions/setup-woocommerce-monorepo
        with:
          build: false

      - name: Tool versions
        run: |
          php --version
          composer --version

      - name: Run code sniffer
        uses: thenabeel/action-phpcs@v8
        with:
          files: "**.php"
          phpcs_path: plugins/woocommerce/vendor/bin/phpcs
          standard: phpcs.xml
