name: 'Label Pull Request Project'
on:
  pull_request_target:
    types:
      - opened
      - synchronize
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  label_project:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/project-pr-labeler.yml
