name: Prime caches against trunk
on: 
  push:
    branches:
      - trunk
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  

jobs:
  prime:
    name: Prime cache
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup WooCommerce Monorepo
        uses: ./.github/actions/setup-woocommerce-monorepo
