name: Smoke test daily
on:
    schedule:
        - cron: '25 3 * * *'
jobs:
    login-run:
        name: Daily smoke test on trunk.
        runs-on: ubuntu-20.04
        steps:
            - name: Create dirs.
              run: |
                  mkdir -p code/woocommerce
                  mkdir -p package/woocommerce
                  mkdir -p tmp/woocommerce

            - name: Checkout code.
              uses: actions/checkout@v3
              with:
                  path: package/woocommerce
                  ref: trunk

            - name: Install prerequisites.
              working-directory: package/woocommerce/plugins/woocommerce
              run: |
                  npm install -g pnpm@^6.24.2
                  pnpm install
                  pnpm nx composer-install-no-dev woocommerce
                  pnpm nx build-assets woocommerce
                  pnpm install jest

            - name: Run smoke test.
              working-directory: package/woocommerce/plugins/woocommerce
              env:
                  SMOKE_TEST_URL: ${{ secrets.SMOKE_TEST_URL }}
                  SMOKE_TEST_ADMIN_USER: ${{ secrets.SMOKE_TEST_ADMIN_USER }}
                  SMOKE_TEST_ADMIN_PASSWORD: ${{ secrets.SMOKE_TEST_ADMIN_PASSWORD }}
                  SMOKE_TEST_ADMIN_USER_EMAIL: ${{ secrets.SMOKE_TEST_ADMIN_USER_EMAIL }}
                  SMOKE_TEST_CUSTOMER_USER: ${{ secrets.SMOKE_TEST_CUSTOMER_USER }}
                  SMOKE_TEST_CUSTOMER_PASSWORD: ${{ secrets.SMOKE_TEST_CUSTOMER_PASSWORD }}
                  WC_E2E_SCREENSHOTS: 1
                  E2E_RETEST: 1
                  E2E_SLACK_TOKEN: ${{ secrets.SMOKE_TEST_SLACK_TOKEN }}
                  E2E_SLACK_CHANNEL: 'C01U0H617MY'
                  UPDATE_WC: 1
                  DEFAULT_TIMEOUT_OVERRIDE: 120000
                  BASE_URL: ${{ secrets.SMOKE_TEST_URL }}
                  USER_KEY: ${{ secrets.SMOKE_TEST_ADMIN_USER }}
                  USER_SECRET: ${{ secrets.SMOKE_TEST_ADMIN_PASSWORD }}
              run: |
                  pnpm exec wc-e2e test:e2e tests/e2e/specs/smoke-tests/update-woocommerce.js
                  pnpm exec wc-e2e test:e2e
                  pnpm exec wc-api-tests test api

    build:
        name: Build zip for PR
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Get cached composer and pnpm directories
              uses: actions/cache@v3
              id: cache-deps
              with:
                path: |
                  ~/.pnpm-store
                  plugins/woocommerce/packages
                  plugins/woocommerce/**/vendor
                key: ${{ runner.os }}-npm-composer-${{ hashFiles('**/composer.lock', '**/pnpm-lock.yaml') }}

            - name: Install PNPM
              run: npm install -g pnpm@^6.24.2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '7.4'

            - name: Build zip
              working-directory: plugins/woocommerce
              run: bash bin/build-zip.sh

            - name: Upload PR zip
              uses: actions/upload-artifact@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  name: woocommerce
                  path: plugins/woocommerce/woocommerce.zip
                  retention-days: 7

    test-plugins:
        name: Smoke tests with ${{ matrix.plugin }} plugin installed
        runs-on: ubuntu-20.04
        needs: [build]
        strategy:
            fail-fast: false
            matrix:
                include:
                    - plugin: 'WooCommerce Payments'
                      repo: 'automattic/woocommerce-payments'
                    - plugin: 'WooCommerce PayPal Payments'
                      repo: 'woocommerce/woocommerce-paypal-payments'
                    - plugin: 'WooCommerce Shipping & Tax'
                      repo: 'automattic/woocommerce-services'
                    - plugin: 'WooCommerce Subscriptions'
                      repo: WC_SUBSCRIPTIONS_REPO
                      private: true
                    - plugin: 'WordPress SEO' # Yoast SEO in the UI, but the slug is wordpress-seo
                      repo: 'Yoast/wordpress-seo'
                    - plugin: 'Contact Form 7'
                      repo: 'takayukister/contact-form-7'
        steps:
            - name: Create dirs.
              run: |
                  mkdir -p code/woocommerce
                  mkdir -p package/woocommerce
                  mkdir -p tmp/woocommerce

            - name: Checkout code.
              uses: actions/checkout@v3
              with:
                  path: package/woocommerce

            - name: Install PNPM and install dependencies
              working-directory: package/woocommerce
              run: |
                  npm install -g pnpm@^6.24.2
                  pnpm install

            - name: Load docker images and start containers.
              working-directory: package/woocommerce/plugins/woocommerce
              run: pnpm exec wc-e2e docker:up

            - name: Move current directory to code. We will install zip file in this dir later.
              run: mv ./package/woocommerce/plugins/woocommerce/* ./code/woocommerce

            - name: Download WooCommerce ZIP.
              uses: actions/download-artifact@v3
              with:
                  name: woocommerce
                  path: tmp

            - name: Extract and replace WooCommerce zip.
              working-directory: tmp
              run: |
                  unzip woocommerce.zip -d woocommerce
                  mv woocommerce/woocommerce/* ../package/woocommerce/plugins/woocommerce/

            - name: Install dependencies again
              working-directory: package/woocommerce
              run: |
                  npm install -g pnpm@^6.24.2
                  pnpm install

            - name: Run tests command.
              working-directory: package/woocommerce/plugins/woocommerce
              env:
                  WC_E2E_SCREENSHOTS: 1
                  E2E_SLACK_TOKEN: ${{ secrets.SMOKE_TEST_SLACK_TOKEN }}
                  E2E_SLACK_CHANNEL: ${{ secrets.RELEASE_TEST_SLACK_CHANNEL }}
                  PLUGIN_REPOSITORY: ${{ matrix.private && secrets[matrix.repo] || matrix.repo }}
                  PLUGIN_NAME: ${{ matrix.plugin }}
                  GITHUB_TOKEN: ${{ secrets.E2E_GH_TOKEN }}
              run: |
                  pnpm exec wc-e2e test:e2e tests/e2e/specs/smoke-tests/upload-plugin.js
                  pnpm exec wc-e2e test:e2e
