name: Smoke test daily
on:
  schedule:
    - cron: '25 3 * * *'
jobs:
  login-run:
    name: Daily smoke test on trunk.
    runs-on: ubuntu-18.04
    steps:

      - name: Create dirs.
        run: |
              mkdir -p code/woocommerce
              mkdir -p package/woocommerce
              mkdir -p tmp/woocommerce
              mkdir -p node_modules

      - name: Checkout code.
        uses: actions/checkout@v2
        with:
          path: package/woocommerce
          ref: trunk

      - name: Install prerequisites.
        working-directory: package/woocommerce/plugins/woocommerce
        run: |
          npm install -g pnpm
          pnpm install
          pnpm nx composer-install-no-dev woocommerce
          pnpm nx build-assets woocommerce
          pnpm install jest
          
      - name: Run smoke test.
        working-directory: package/woocommerce/plugins/woocommerce
        env:
          SMOKE_TEST_URL: ${{ secrets.SMOKE_TEST_URL }}
          SMOKE_TEST_ADMIN_USER: ${{ secrets.SMOKE_TEST_ADMIN_USER }}
          SMOKE_TEST_ADMIN_PASSWORD: ${{ secrets.SMOKE_TEST_ADMIN_PASSWORD }}
          SMOKE_TEST_ADMIN_USER_EMAIL: ${{ secrets.SMOKE_TEST_ADMIN_USER_EMAIL }}
          SMOKE_TEST_CUSTOMER_USER: ${{ secrets.SMOKE_TEST_CUSTOMER_USER }}
          SMOKE_TEST_CUSTOMER_PASSWORD: ${{ secrets.SMOKE_TEST_CUSTOMER_PASSWORD }}
          WC_E2E_SCREENSHOTS: 1
          E2E_RETEST: 1
          E2E_SLACK_TOKEN: ${{ secrets.SMOKE_TEST_SLACK_TOKEN }}
          E2E_SLACK_CHANNEL: ${{ secrets.SMOKE_TEST_SLACK_CHANNEL }}
          UPDATE_WC: 1
          DEFAULT_TIMEOUT_OVERRIDE: 120000
          BASE_URL: ${{ secrets.SMOKE_TEST_URL }}
          USER_KEY: ${{ secrets.SMOKE_TEST_ADMIN_USER }}
          USER_SECRET: ${{ secrets.SMOKE_TEST_ADMIN_PASSWORD }}
        run: |
          pnpx wc-e2e test:e2e plugins/woocommerce/tests/e2e/specs/smoke-tests/update-woocommerce.js
          pnpx wc-e2e test:e2e
          pnpx wc-api-tests test api

  build:
    name: Build zip for PR
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build
          id: build
          uses: woocommerce/action-build@trunk
          env:
              BUILD_ENV: e2e

        - name: Upload PR zip
          uses: actions/upload-artifact@v2
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              name: woocommerce
              path: ${{ steps.build.outputs.zip_path }}
              retention-days: 7
    
  test-plugins:
    name: Smoke tests with ${{ matrix.plugin }} plugin installed
    runs-on: ubuntu-18.04
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        include:
          - plugin: 'WooCommerce Payments'
            repo: 'automattic/woocommerce-payments'
          - plugin: 'Facebook for WooCommerce'
            repo: 'woocommerce/facebook-for-woocommerce'
          - plugin: 'WooCommerce Shipping & Tax'
            repo: 'woocommerce/woocommerce-services'
          - plugin: 'WooCommerce Subscriptions'
            repo: WC_SUBSCRIPTIONS_REPO
            private: true
          - plugin: 'WordPress SEO' # Yoast SEO in the UI, but the slug is wordpress-seo
            repo: 'Yoast/wordpress-seo'
          - plugin: 'Contact Form 7'
            repo: 'takayukister/contact-form-7'
    steps:
      - name: Create dirs.
        run: |
            mkdir -p code/woocommerce
            mkdir -p package/woocommerce
            mkdir -p tmp/woocommerce
            mkdir -p node_modules

      - name: Checkout code.
        uses: actions/checkout@v2
        with:
            path: package/woocommerce

      - name: Install PNPM and install dependencies
        working-directory: package/woocommerce
        run: |
            npm install -g pnpm
            pnpm install

      - name: Load docker images and start containers.
        working-directory: package/woocommerce/plugins/woocommerce
        run: pnpx wc-e2e docker:up

      - name: Move current directory to code. We will install zip file in this dir later.
        run: mv ./package/woocommerce/plugins/woocommerce/* ./code/woocommerce

      - name: Download WooCommerce ZIP.
        uses: actions/download-artifact@v2
        with:
            name: woocommerce
            path: tmp

      - name: Extract and replace WooCommerce zip.
        working-directory: tmp
        run: |
            unzip woocommerce.zip -d woocommerce
            mv woocommerce/woocommerce/* ../package/woocommerce/plugins/woocommerce/

      - name: Install dependencies again
        working-directory: package/woocommerce
        run: |
            npm install -g pnpm
            pnpm install

      - name: Run tests command.
        working-directory: package/woocommerce/plugins/woocommerce
        env:
          WC_E2E_SCREENSHOTS: 1
          E2E_SLACK_TOKEN: ${{ secrets.SMOKE_TEST_SLACK_TOKEN }}
          E2E_SLACK_CHANNEL: ${{ secrets.RELEASE_TEST_SLACK_CHANNEL }}
          GITHUB_REPOSITORY: ${{ matrix.private && secrets[matrix.repo] || matrix.repo }}
          PLUGIN_NAME: ${{ matrix.plugin }}
          GITHUB_TOKEN: ${{ secrets.E2E_GH_TOKEN }}
        run: |
          pnpx wc-e2e test:e2e plugins/woocommerce/tests/e2e/specs/smoke-tests/upload-plugin.js
          pnpm nx test-e2e woocommerce
