name: Smoke test release test
on:
  workflow_dispatch:
    inputs:
      release_id:
        description: WooCommerce Release Id
        required: true
jobs:
  login-run:
    name: Daily smoke test on release.
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
        with:
          path: package/woocommerce
      - name: Fetch Asset ID
        id: fetch_asset_id
        uses: actions/github-script@v5
        env:
          RELEASE_ID: ${{ github.event.inputs.release_id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        with:
          script: |
            const script = require( './package/woocommerce/.github/workflows/scripts/fetch-asset-id.js' )
            await script({github, context, core})
      - name: Download WooCommerce release zip
        run: |
          echo ${{ steps.fetch_asset_id.outputs.asset_id }}

          curl -u ${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }} https://api.github.com/repos/${{ github.repository }}/releases/assets/${{ steps.fetch_asset_id.outputs.asset_id }} -LJOH 'Accept: application/octet-stream'

          unzip woocommerce.zip -d woocommerce
          ls woocommerce
           

    
